/**
 * English. Traducción de `es.ts`, que es la tabla de referencia.
 *
 * El tipo obliga a tenerlas todas: si se añade una frase en español y aquí
 * falta, TypeScript avisa al compilar en vez de dejar un hueco.
 */
import type { es } from './es';

export const en: Record<keyof typeof es, string> = {
  // ---------------------------------------------------------- navegación
  'tab.alumnos': 'Athletes',
  'tab.plan': 'Plan',
  'tab.actividades': 'Activities',
  'tab.iniciar': 'Start',
  'tab.chat': 'Chat',
  'tab.cuenta': 'Account',

  // ---------------------------------------------------------- cabeceras
  'alumnos.titulo': 'Athletes',
  'alumnos.frase': 'Manage your athletes, build their plans and take their progress further.',
  'alumnos.enTrenamiento': 'Training',
  'alumnos.sinPlan': 'No plan',
  'alumnos.vacio': 'No athletes yet. Share your invite link.',
  'plan.titulo': 'My plan',
  'plan.frase': 'What you have got this week. Tick it off and go run.',
  'actividades.titulo': 'Activities',
  'actividades.frase': 'Everything you have run, walked and trained.',
  'iniciar.titulo': 'Start',
  'iniciar.frase': 'Record your session with GPS. It keeps measuring with the screen off.',
  'chat.titulo': 'Messages',
  'chat.fraseCoach': 'Talk to your athletes, answer questions and adjust the plan.',
  'chat.fraseAtleta': 'Message your coach whenever you need to.',
  'cuenta.titulo': 'Account',
  'cuenta.frase': 'Your profile, your heart rate zones and the Strava connection.',
  'servicios.titulo': 'Services',
  'servicios.frase': 'Real coaching, inside and outside the app.',

  // ---------------------------------------------------------- invitar
  'invitar.titulo': 'Invite athletes',
  'invitar.desc': 'Share the link and add them to your group.',
  'invitar.copiar': 'Copy',
  'invitar.copiado': 'Copied',
  'invitar.compartir': 'Join my training group on MyCoachRuns: {link}',

  // ---------------------------------------------------------- entrar
  'entrar.lema': 'Your coach sets the plan. You go out and run.',
  'entrar.entrar': 'Sign in',
  'entrar.crear': 'Create account',
  'entrar.sinClave': 'No password',
  'entrar.correo': 'Email',
  'entrar.clave': 'Password',
  'entrar.clavePista': 'At least 6 characters',
  'entrar.nombre': 'Name',
  'entrar.nombrePista': 'What your coach calls you',
  'entrar.codigo': 'Coach code (optional)',
  'entrar.codigoPista': 'Your coach gives it to you',
  'entrar.espera': 'One moment…',
  'entrar.enviarEnlace': 'Send link',
  'entrar.olvide': 'I forgot my password',
  'entrar.mandarCorreo': 'Email me the link',
  'entrar.volverClave': 'Go back to signing in with a password',
  'entrar.pocosCorreos': 'The email takes a couple of minutes. Only a few can be sent per hour.',
  'entrar.instalar': 'To install it: in your browser tap «Share» → «Add to Home Screen».',
  'entrar.invita': '{nombre} invites you to train. Create your account and you will join their group.',
  'entrar.sesionRota': 'Your session was left half done. Sign in again with your email and password.',
  'entrar.limpiar': 'Clear session',
  'entrar.noSesion': 'We could not check your session.',
  'entrar.malClave': 'Wrong email or password.',
  'entrar.muchosCorreos': 'Too many emails in a row. Wait a while or sign in with a password.',
  'entrar.yaExiste': 'There is already an account with that email. Sign in from the «Sign in» tab.',
  'entrar.revisaCorreo': 'Account created. Check your email to confirm it, then sign in with your password.',
  'entrar.enlaceEnviado': 'We sent a link to your email.',
  'entrar.recuperaEnviado': 'We sent you an email. Open it on this same phone and it will take you to set a new password. If it does not arrive in a few minutes, check your spam folder.',

  // ---------------------------------------------------------- grabar
  'grabar.queHacer': 'WHAT ARE YOU DOING?',
  'grabar.comoHacer': 'HOW ARE YOU DOING IT',
  'grabar.libre': 'Free',
  'grabar.sinAsignar': 'No workout assigned',
  'grabar.yaMarcado': 'already done',
  'grabar.hoy': 'Today',
  'grabar.fases': '{n} phases',
  'grabar.correr': 'Run',
  'grabar.caminata': 'Walk',
  'grabar.trail': 'Trail',
  'grabar.enMarcha': 'Running',
  'grabar.enPausa': 'Paused',
  'grabar.terminada': 'Finished',
  'grabar.sinConexion': 'Offline: this is the last thing saved on the phone.',

  // ---------------------------------------------------------- tipos
  'tipo.easy': 'Easy run',
  'tipo.long': 'Long run',
  'tipo.tempo': 'Tempo',
  'tipo.intervals': 'Intervals',
  'tipo.trail': 'Trail',
  'tipo.walk': 'Walk',
  'tipo.race': 'Race',
  'tipo.strength': 'Strength',
  'tipo.rest': 'Rest',

  // ---------------------------------------------------------- servicios
  'serv.pacingTitulo': 'Race pacing · 5K to 10K',
  'serv.pacingDesc': 'I run with you and hold the agreed pace, so you neither go out too fast nor fade at the end.',
  'serv.pacing1': 'Events and road races',
  'serv.pacing2': 'Groups chasing a shared time',
  'serv.pacing3': 'One person, at your target pace',
  'serv.unoTitulo': '1-to-1 coaching',
  'serv.unoDesc': 'A plan built for you and adjusted week by week to how you are responding, not a template everyone gets.',
  'serv.uno1': 'Structured sessions in the app, with voice cues',
  'serv.uno2': 'Follow-up on your runs and your effort',
  'serv.uno3': 'Direct contact through the chat',
  'serv.precioTitulo': 'How much is it?',
  'serv.precioDesc': 'It depends on the distance, the dates and whether it is for one person or a group. Write to me and we will talk it over, no strings: I will tell you what fits you and what it would cost.',
  'serv.whatsapp': 'Message me on WhatsApp',
  'serv.correo': 'Email me',
  'serv.saludoWa': 'Hi, I am writing from MyCoachRuns. I am interested in your services.',
  'serv.asuntoCorreo': 'Question about MyCoachRuns services',

  // ---------------------------------------------------------- menú
  'menu.abrir': 'Open menu',
  'menu.cerrar': 'Close',
  'menu.serviciosDesc': 'Race pacing and 1-to-1 coaching',
  'menu.cuentaDesc': 'Your profile, heart rate and Strava',
  'menu.escribenos': 'Write to us',
  'menu.instagram': 'Instagram',
  'menu.strava': 'Strava',
  'menu.stravaDesc': 'Follow the developer',
  'menu.apoyar': 'Support the project',
  'menu.apoyarDesc': 'Buy me a coffee',

  // ---------------------------------------------------------- cuenta
  'cuenta.idioma': 'Language',
  'cuenta.idiomaDesc': 'Change the language of the app and of the voice cues.',

  // ---------------------------------------------------------- comunes
  'com.guardar': 'Save',
  'com.cancelar': 'Cancel',
  'com.cerrar': 'Close',
  'com.actualizar': 'Update',
  'com.reintentar': 'Try again',
  'com.sinRed': 'We could not reach the server. Check your connection.',
  'com.sinRedServidor': 'We could not reach the server ({url}). Check that the phone has internet.',
  'com.algoFallo': 'Something failed and did not say why.',
  'com.sesionCaducada': 'Your session expired. Sign in again.',

  // ---------------------------------------------------------- voz
  'voz.empezamos': 'Here we go.',
  'voz.alDia': 'All caught up.',
  'voz.kilometro': 'Kilometer {n}. Average pace {ritmo} per kilometer',
  'voz.pulsoMedio': ', heart rate {ppm}',
  'voz.entreRitmos': ', at a pace between {a} and {b} per kilometer',
  'voz.unRitmo': ', at a pace of {a} per kilometer',
  'voz.zonaPulso': ', in heart rate zone {n}',
  'voz.minutos': '{n} minutes',
  'voz.unMinuto': '1 minute',
  'voz.segundos': '{n} seconds',
  'voz.minutosYsegundos': '{m} and {s} seconds',
  'voz.metros': '{n} meters',
  'voz.kilometros': '{n} kilometers',
  'voz.coma': ' point ',
  'voz.de': ' of ',
  'voz.horas': '{n} hours',
  'voz.unaHora': '1 hour',
  'voz.buenaCarrera': 'Have a good run.',
  'voz.seguimos': 'Carrying on.',
  'voz.enPausa': 'Paused.',
  'voz.completado': 'Workout complete. Good job.',
  'voz.terminada': 'Activity finished. {dist} in {tiempo}.',

  // ------------------------------------------ el resto de la app
  'rec.verResumen': 'Show summary',
  'rec.verRepes': 'Show every rep',
  'rec.saltarFase': 'Skip to the next phase',
  'rec.completado': 'Workout complete.',
  'rec.completadoDesc': 'You can keep running or tap Finish.',
  'rec.sensor': 'Sensor: {n}',
  'rec.conectarPulso': 'Connect heart rate strap',
  'rec.iniciarEntreno': 'Start workout ({n} phases)',
  'rec.iniciarLibre': 'Start a free run',
  'rec.pausar': 'Pause',
  'rec.continuar': 'Resume',
  'rec.terminar': 'Finish',
  'rec.comoSintio': 'How did it feel?',
  'rec.rpeVacio': 'Perceived effort (optional)',
  'rec.notasPista': 'Notes for your coach (optional)',
  'rec.guardarStrava': 'Save and upload to Strava',
  'rec.guardarSolo': 'Save only in MyCoachRuns',
  'rec.descartarPregunta': 'Discard this run? It cannot be recovered.',
  'rec.descartar': 'Discard',
  'rec.guardando': 'Saving…',
  'rec.verActividades': 'See my activities',
  'rec.grabarOtra': 'Record another',
  'rec.sinGps': 'This browser has no GPS.',
  'rpe.1': 'Very easy',
  'rpe.2': 'Easy',
  'rpe.3': 'Comfortable',
  'rpe.4': 'Slightly hard',
  'rpe.5': 'Moderate',
  'rpe.6': 'Hard',
  'rpe.7': 'Tough',
  'rpe.8': 'Very tough',
  'rpe.9': 'Almost maximal',
  'rpe.10': 'Maximal',
  'plan.borrarPregunta': 'Delete this workout?',
  'plan.vacio': 'There are no workouts in the plan yet.',
  'plan.estaSemana': 'This week',
  'plan.hecho': 'Done',
  'plan.deshacer': 'Undo',
  'plan.marcarHecho': 'Mark as done',
  'plan.ocultarFases': 'Hide phases',
  'plan.verFases': 'Show {n} phases',
  'plan.descargarFit': 'Download .FIT',
  'plan.comoGarmin': 'How do I get it onto my Garmin?',
  'plan.ocultarMusculos': 'Hide muscles',
  'plan.verMusculos': 'Show {n} muscles',
  'plan.copiar': 'Copy',
  'plan.copiado': 'Copied',
  'plan.editar': 'Edit',
  'plan.borrar': 'Delete',
  'plan.garminAviso': 'Do not upload it through the Garmin Connect website: that only imports activities you have already done, and it would show up as a route.',
  'plan.garmin1': '1. Connect the watch to the computer with the USB cable.',
  'plan.garmin2': '2. Open the watch drive and go to',
  'plan.garmin3': '3. Copy the .FIT in there and unplug the watch.',
  'plan.garmin4': '4. On the watch: Training → Workouts.',
  'act.parciales': 'SPLITS BY KM',
  'act.vacio': 'No activities yet. The ones you record here or upload to Strava will show up in this list.',
  'act.sinNombre': 'Activity',
  'act.verStrava': 'View on Strava',
  'chat.noEnviado': 'It could not be sent. Try again.',
  'chat.cargando': 'Loading…',
  'chat.vacio': 'No messages with {nombre} yet. Write the first one.',
  'chat.pista': 'Message for {nombre}',
  'chat.enviar': 'Send',
  'cuenta.guardando': 'Saving…',
  'cuenta.guardado': 'Saved.',
  'cuenta.noGuardado': 'It could not be saved.',
  'cuenta.nombre': 'Name',
  'cuenta.codigo': 'Coach code',
  'cuenta.codigoPista': 'Paste your coach’s code here',
  'cuenta.clave': 'Password',
  'cuenta.claveDesc': 'Set a password so you can sign in on the phone without waiting for an email.',
  'cuenta.clavePista': 'New password (min. 6)',
  'cuenta.guardarClave': 'Save password',
  'cuenta.claveGuardada': 'Password saved. You can now sign in from any device.',
  'cuenta.zonas': 'Heart rate zones',
  'cuenta.zonasDesc': 'With this the app tells you whether you are inside the zone your coach asked for.',
  'cuenta.pulsoMax': 'Maximum heart rate',
  'cuenta.pulsoReposo': 'Resting heart rate',
  'cuenta.guardarZonas': 'Save zones',
  'cuenta.zonasGuardadas': 'Zones saved.',
  'cuenta.strava': 'Strava',
  'cuenta.stravaOk': 'Connected (athlete {id}). New runs arrive on their own.',
  'cuenta.desconectarStrava': 'Disconnect Strava',
  'cuenta.desconectarPregunta': 'Disconnect Strava? Your runs will stop arriving automatically. The ones already saved stay.',
  'cuenta.desconectando': 'Disconnecting…',
  'cuenta.stravaFuera': 'Strava disconnected.',
  'cuenta.noDesconectado': 'It could not be disconnected.',
  'cuenta.conectarStrava': 'Connect with Strava',
  'cuenta.sesion': 'Session',
  'cuenta.salir': 'Sign out',
  'push.titulo': 'Notifications',
  'push.noSoportado': 'This browser does not support notifications. On iPhone, first add MyCoachRuns to the Home Screen and open it from there.',
  'push.bloqueado': 'You blocked them in this browser. Turn them on in the site settings and come back here.',
  'push.off': 'Get a heads-up when your coach assigns or changes a workout.',
  'push.activar': 'Turn on notifications',
  'push.on': 'On for this device.',
  'push.desactivar': 'Turn off',
  'push.listo': 'Done. We will let you know when your coach changes something.',
  'push.faltaLlave': 'The notification key is not set up on the server.',
  'push.noGuardado': 'The subscription could not be saved.',
  'form.fecha': 'Date',
  'form.tipo': 'Type',
  'form.tambienA': 'Also assign to',
  'form.sinNombre': 'No name',
  'form.musculos': 'Muscles worked',
  'form.titulo': 'Title',
  'form.tituloPista': 'e.g. 6×800 intervals',
  'form.fases': 'Phases',
  'form.fasesDesc': 'The athlete sees them one by one while running, with a cue at the end of each.',
  'form.notas': 'Notes',
  'form.notasPista': 'Sensations to look for, kit, terrain…',
  'form.guardarCambios': 'Save changes',
  'form.asignar': 'Assign',
  'form.tardo': 'The server took too long. Check your connection and try again.',
  'fase.calentamiento': 'Warm-up',
  'fase.trabajo': 'Work',
  'fase.recuperacion': 'Recovery',
  'fase.enfriamiento': 'Cool-down',
  'fase.pausa': 'Stop',
  'fase.subir': 'Move up',
  'fase.bajar': 'Move down',
  'fase.duplicar': 'Duplicate',
  'fase.borrarPregunta': 'Delete the phase "{nombre}"?',
  'fase.anadir': 'Add',
  'fase.repeticiones': 'Repetitions',
  'fase.nombre': 'Name',
  'fase.nombrePista': 'e.g. 200 hard',
  'fase.medirPor': 'Measure by',
  'fase.distancia': 'Distance (km)',
  'fase.tiempo': 'Time (min)',
  'fase.kilometros': 'Kilometers',
  'fase.minutos': 'Minutes',
  'fase.ritmoRapido': 'Fast pace',
  'fase.ritmoLento': 'Slow pace',
  'fase.zona': 'Heart rate zone (optional)',
  'fase.sinZona': 'No target zone',
  'fase.zona1': 'Zone 1 — Recovery',
  'fase.zona2': 'Zone 2 — Easy aerobic',
  'fase.zona3': 'Zone 3 — Strong aerobic',
  'fase.zona4': 'Zone 4 — Threshold',
  'fase.zona5': 'Zone 5 — Maximum',
  'fase.nombreRecu': 'Recovery name',
  'fase.troteSuave': 'Easy jog',
  'pegar.copiado': 'WORKOUT COPIED',
  'pegar.otraFecha': 'Paste another date',
  'pegar.quitarCopia': 'Remove copy',
  'pegar.pegando': 'Pasting…',
  'pegar.enPlan': 'Paste into {nombre}’s plan',
  'pegar.quitar': 'Remove',
  'pegar.noPegado': 'It could not be pasted.',
  'pegar.noPegadoRed': 'It could not be pasted. Check your connection.',
  'pegar.aviso': 'You have {titulo} copied. Open an athlete to paste it into their plan.',
  'refr.actualizando': 'Refreshing…',
  'refr.suelta': 'Release to refresh',
  'refr.tira': 'Pull to refresh',
  'musc.marcados': 'Selected:',
  'musc.toca': 'Tap the muscles on the drawing or in the list.',
  'img.creando': 'Making the image…',
  'img.guardar': 'Save or share image',
  'img.noCreada': 'The image could not be created.',
  'img.noGuardada': 'The image could not be saved.',
  'img.crearFoto': 'Make a photo with my data',
  'img.creandoCorto': 'Making image…',
  'img.guardarCorto': 'Save or share',
  'img.otraFoto': 'Another photo',
  'img.manten': 'You can also press and hold the image to save it.',
  'avatar.subiendo': 'Uploading…',
  'avatar.cambiar': 'Change photo',
  'avatar.subir': 'Upload photo',
  'avatar.hecho': 'Photo updated.',
  'avatar.fallo': 'The photo could not be uploaded.',
  'zona.1': 'Recovery',
  'zona.2': 'Easy aerobic',
  'zona.3': 'Strong aerobic',
  'zona.4': 'Threshold',
  'zona.5': 'Maximum',
  'rec.pasoAPaso': 'STEP BY STEP',
  'rec.bloques': 'WORKOUT · {n} BLOCKS',
  'rec.unBloque': 'WORKOUT · 1 BLOCK',
  'rec.nFases': 'WORKOUT · {n} PHASES',
  'rec.enZona': 'In zone',
  'rec.pulsoAlto': 'Heart rate high',
  'rec.pulsoBajo': 'Heart rate low',
  'rec.tiempo': 'time',
  'rec.zonaPpm': '· zone {n} {nombre}',
  'rec.precision': 'GPS accuracy: ±{m} m',
  'rec.senalDebil': '— weak signal, the distance may come up short',
  'rec.avisosVoz': 'Voice and sound cues at every kilometer',
  'rec.subirStrava': 'Upload to Strava as well',
  'act.desnivel': 'm climb',
  'act.esfuerzo': 'Effort {n}/10',
  'musc.pecho': 'Chest',
  'musc.hombros': 'Shoulders',
  'musc.biceps': 'Biceps',
  'musc.antebrazos': 'Forearms',
  'musc.abdomen': 'Abs',
  'musc.oblicuos': 'Obliques',
  'musc.cuadriceps': 'Quads',
  'musc.aductores': 'Adductors',
  'musc.tibial': 'Shins',
  'musc.trapecio': 'Traps',
  'musc.dorsal': 'Lats',
  'musc.lumbar': 'Lower back',
  'musc.triceps': 'Triceps',
  'musc.gluteos': 'Glutes',
  'musc.isquios': 'Hamstrings',
  'musc.gemelos': 'Calves',
  'img.fuerza': 'Strength',
  'desc.ritmo': ' at {a} /km',
  'desc.zona': ' · zone {n}',
  'desc.recu': ' · recovery {cant}',
  'desc.parado': ' standing',
  'fase.pasos': '{n} steps · {km} km · ~{min} min',
  'fase.anadirFase': '+ Add phase',
  'fase.recuEntre': 'Recovery between reps',
  'fase.trotando': 'Jogging (uncheck it for a full stop)',
  'fase.trasUltima': 'Include it after the last rep too',
  'pie.escribenos': 'Write to us',
  'pie.apoyar': 'Support the project',
  'pie.lema': 'MyCoachRuns · Train, improve, move forward',
  'entrar.servidorDijo': 'The server answered {n} when checking your session.',
  'alumnos.sinNombre': 'No name',
  'plan.conectaStrava': 'Connect Strava so your runs sync on their own.',
  'plan.conectar': 'Connect',
  'plan.sinCoach': 'You are not linked to a coach yet. Ask them for their invite link.',
  'chat.sinCargar': 'The messages could not be loaded. They need a connection.',
  'chat.sinCoach': 'You are not linked to a coach yet, so there is nobody to talk to.',
  'chat.sinAlumnos': 'You have no athletes yet.',
  'chat.sinLeer': '{n} unread',
  'chat.alDia': 'All caught up',
  'alumno.stravaOk': 'Strava connected',
  'alumno.sinStrava': 'No Strava',
  'alumno.asignar': 'Assign a workout',
} as const;
