/**
 * Las frases en español. **Esta es la tabla de referencia**: las demás son
 * traducciones de esta, y si a una le falta una clave, cae aquí.
 *
 * Al añadir una frase nueva se añade aquí primero; TypeScript avisará en las
 * otras tablas si falta.
 *
 * Las piezas variables van como `{nombre}` y las rellena `t()`.
 */
export const es = {
  // ---------------------------------------------------------- navegación
  'tab.alumnos': 'Alumnos',
  'tab.plan': 'Plan',
  'tab.actividades': 'Actividades',
  'tab.iniciar': 'Iniciar',
  'tab.chat': 'Chat',
  'tab.cuenta': 'Cuenta',

  // ---------------------------------------------------------- cabeceras
  'alumnos.titulo': 'Alumnos',
  'alumnos.frase': 'Gestiona tus atletas, crea planes y lleva su progreso al siguiente nivel.',
  'alumnos.enTrenamiento': 'En entrenamiento',
  'alumnos.sinPlan': 'Sin plan',
  'alumnos.vacio': 'Aún no tienes alumnos. Comparte tu enlace de invitación.',
  'plan.titulo': 'Mi plan',
  'plan.frase': 'Lo que toca esta semana. Marca lo hecho y sal a correr.',
  'actividades.titulo': 'Actividades',
  'actividades.frase': 'Todo lo que has corrido, caminado y entrenado.',
  'iniciar.titulo': 'Iniciar',
  'iniciar.frase': 'Graba tu sesión con GPS. Sigue midiendo con la pantalla apagada.',
  'chat.titulo': 'Mensajes',
  'chat.fraseCoach': 'Habla con tus alumnos, resuelve dudas y ajusta el plan.',
  'chat.fraseAtleta': 'Escríbele a tu entrenador cuando lo necesites.',
  'cuenta.titulo': 'Cuenta',
  'cuenta.frase': 'Tu perfil, tus zonas de pulso y la conexión con Strava.',
  'servicios.titulo': 'Servicios',
  'servicios.frase': 'Acompañamiento de verdad, dentro y fuera de la app.',

  // ---------------------------------------------------------- invitar
  'invitar.titulo': 'Invitar alumnos',
  'invitar.desc': 'Comparte el enlace y súmalos a tu grupo.',
  'invitar.copiar': 'Copiar',
  'invitar.copiado': 'Copiado',
  'invitar.compartir': 'Únete a mi grupo de entrenamiento en MyCoachRuns: {link}',

  // ---------------------------------------------------------- entrar
  'entrar.lema': 'Tu entrenador te pone el plan. Tú sales a correr.',
  'entrar.entrar': 'Entrar',
  'entrar.crear': 'Crear cuenta',
  'entrar.sinClave': 'Sin contraseña',
  'entrar.correo': 'Correo',
  'entrar.clave': 'Contraseña',
  'entrar.clavePista': 'Mínimo 6 caracteres',
  'entrar.nombre': 'Nombre',
  'entrar.nombrePista': 'Como te llama tu entrenador',
  'entrar.codigo': 'Código de entrenador (opcional)',
  'entrar.codigoPista': 'Te lo pasa tu coach',
  'entrar.espera': 'Un momento…',
  'entrar.enviarEnlace': 'Enviar enlace',
  'entrar.olvide': 'Olvidé mi contraseña',
  'entrar.mandarCorreo': 'Mandarme el correo',
  'entrar.volverClave': 'Volver a entrar con contraseña',
  'entrar.pocosCorreos': 'El correo tarda un par de minutos. Solo se pueden mandar unos pocos por hora.',
  'entrar.instalar': 'Para instalarla: en el navegador toca «Compartir» → «Añadir a pantalla de inicio».',
  'entrar.invita': '{nombre} te invita a entrenar. Crea tu cuenta y quedarás en su grupo.',
  'entrar.sesionRota': 'Tu sesión quedó a medias. Entra otra vez con tu correo y contraseña.',
  'entrar.limpiar': 'Limpiar sesión',
  'entrar.noSesion': 'No se pudo comprobar tu sesión.',
  'entrar.malClave': 'Correo o contraseña incorrectos.',
  'entrar.muchosCorreos': 'Demasiados correos seguidos. Espera un rato o entra con contraseña.',
  'entrar.yaExiste': 'Ya existe una cuenta con ese correo. Entra desde la pestaña «Entrar».',
  'entrar.revisaCorreo': 'Cuenta creada. Revisa tu correo para confirmarla y luego entra con tu contraseña.',
  'entrar.enlaceEnviado': 'Te enviamos un enlace al correo.',
  'entrar.recuperaEnviado': 'Te mandamos un correo. Ábrelo desde este mismo teléfono y te llevará a ponerte una contraseña nueva. Si no llega en unos minutos, mira en la carpeta de correo no deseado.',

  // ---------------------------------------------------------- grabar
  'grabar.queHacer': '¿QUÉ VAS A HACER?',
  'grabar.comoHacer': 'CÓMO LO VAS A HACER',
  'grabar.libre': 'Libre',
  'grabar.sinAsignar': 'Sin entrenamiento asignado',
  'grabar.yaMarcado': 'ya marcado',
  'grabar.hoy': 'Hoy',
  'grabar.fases': '{n} fases',
  'grabar.correr': 'Correr',
  'grabar.caminata': 'Caminata',
  'grabar.trail': 'Trail',
  'grabar.enMarcha': 'En marcha',
  'grabar.enPausa': 'En pausa',
  'grabar.terminada': 'Terminada',
  'grabar.sinConexion': 'Sin conexión: esto es lo último que se guardó en el teléfono.',

  // ---------------------------------------------------------- tipos
  'tipo.easy': 'Rodaje suave',
  'tipo.long': 'Fondo',
  'tipo.tempo': 'Tempo',
  'tipo.intervals': 'Series',
  'tipo.trail': 'Trail',
  'tipo.walk': 'Caminata',
  'tipo.race': 'Carrera',
  'tipo.strength': 'Fuerza',
  'tipo.rest': 'Descanso',

  // ---------------------------------------------------------- servicios
  'serv.pacingTitulo': 'Pacing en carrera · 5K a 10K',
  'serv.pacingDesc': 'Corro contigo y te llevo al ritmo acordado, para que no salgas demasiado rápido ni te quedes corto al final.',
  'serv.pacing1': 'Eventos y carreras populares',
  'serv.pacing2': 'Grupos que buscan una marca en común',
  'serv.pacing3': 'Una sola persona, a tu ritmo objetivo',
  'serv.unoTitulo': 'Entrenamiento 1 a 1',
  'serv.unoDesc': 'Un plan hecho para ti y ajustado semana a semana según cómo vayas respondiendo, no una plantilla igual para todos.',
  'serv.uno1': 'Sesiones estructuradas en la app, con avisos por voz',
  'serv.uno2': 'Seguimiento de tus carreras y de tu esfuerzo',
  'serv.uno3': 'Contacto directo por el chat',
  'serv.precioTitulo': '¿Cuánto cuesta?',
  'serv.precioDesc': 'Depende de la distancia, de las fechas y de si es para una persona o para un grupo. Escríbeme y lo hablamos sin compromiso: te digo qué encaja contigo y cuánto sería.',
  'serv.whatsapp': 'Escríbeme por WhatsApp',
  'serv.correo': 'Escríbeme por correo',
  'serv.saludoWa': 'Hola, te escribo desde MyCoachRuns. Me interesan tus servicios.',
  'serv.asuntoCorreo': 'Consulta sobre los servicios de MyCoachRuns',

  // ---------------------------------------------------------- menú
  'menu.abrir': 'Abrir menú',
  'menu.cerrar': 'Cerrar',
  'menu.serviciosDesc': 'Pacing en carrera y entrenamiento 1 a 1',
  'menu.cuentaDesc': 'Tu perfil, pulso y Strava',
  'menu.escribenos': 'Escríbenos',
  'menu.instagram': 'Instagram',
  'menu.strava': 'Strava',
  'menu.stravaDesc': 'Sigue al desarrollador',
  'menu.apoyar': 'Apoyar el proyecto',
  'menu.apoyarDesc': 'Invítame un café',

  // ---------------------------------------------------------- cuenta
  'cuenta.idioma': 'Idioma',
  'cuenta.idiomaDesc': 'Cambia el idioma de la app y de los avisos por voz.',

  // ---------------------------------------------------------- comunes
  'com.guardar': 'Guardar',
  'com.cancelar': 'Cancelar',
  'com.cerrar': 'Cerrar',
  'com.actualizar': 'Actualizar',
  'com.reintentar': 'Reintentar',
  'com.sinRed': 'No se pudo hablar con el servidor. Comprueba tu conexión.',
  'com.sinRedServidor': 'No se pudo hablar con el servidor ({url}). Comprueba que el teléfono tiene internet.',
  'com.algoFallo': 'Algo falló y no dijo por qué.',
  'com.sesionCaducada': 'Tu sesión caducó. Entra de nuevo.',

  // ---------------------------------------------------------- voz
  'voz.empezamos': 'Empezamos.',
  'voz.alDia': 'Al día.',
  'voz.kilometro': 'Kilómetro {n}. Ritmo medio {ritmo} por kilómetro',
  'voz.pulsoMedio': ', pulso {ppm}',
  'voz.entreRitmos': ', a ritmo entre {a} y {b} por kilómetro',
  'voz.unRitmo': ', a ritmo de {a} por kilómetro',
  'voz.zonaPulso': ', en zona {n} de pulso',
  'voz.minutos': '{n} minutos',
  'voz.unMinuto': '1 minuto',
  'voz.segundos': '{n} segundos',
  'voz.minutosYsegundos': '{m} y {s} segundos',
  'voz.metros': '{n} metros',
  'voz.kilometros': '{n} kilómetros',
  'voz.coma': ' coma ',
  'voz.de': ' de ',
  'voz.horas': '{n} horas',
  'voz.unaHora': '1 hora',
  'voz.buenaCarrera': 'Buena carrera.',
  'voz.seguimos': 'Seguimos.',
  'voz.enPausa': 'En pausa.',
  'voz.completado': 'Entrenamiento completado. Buen trabajo.',
  'voz.terminada': 'Actividad terminada. {dist} en {tiempo}.',

  // ------------------------------------------ el resto de la app
  'rec.verResumen': 'Ver resumen',
  'rec.verRepes': 'Ver cada repetición',
  'rec.saltarFase': 'Saltar a la siguiente fase',
  'rec.completado': 'Entrenamiento completado.',
  'rec.completadoDesc': 'Puedes seguir corriendo o pulsar Terminar.',
  'rec.sensor': 'Sensor: {n}',
  'rec.conectarPulso': 'Conectar cinturón de pulso',
  'rec.iniciarEntreno': 'Iniciar entrenamiento ({n} fases)',
  'rec.iniciarLibre': 'Iniciar carrera libre',
  'rec.pausar': 'Pausar',
  'rec.continuar': 'Continuar',
  'rec.terminar': 'Terminar',
  'rec.comoSintio': '¿Cómo se sintió?',
  'rec.rpeVacio': 'Esfuerzo percibido (opcional)',
  'rec.notasPista': 'Notas para tu entrenador (opcional)',
  'rec.guardarStrava': 'Guardar y subir a Strava',
  'rec.guardarSolo': 'Guardar solo en MyCoachRuns',
  'rec.descartarPregunta': '¿Descartar esta carrera? No se podrá recuperar.',
  'rec.descartar': 'Descartar',
  'rec.guardando': 'Guardando…',
  'rec.verActividades': 'Ver mis actividades',
  'rec.grabarOtra': 'Grabar otra',
  'rec.sinGps': 'Este navegador no tiene GPS.',
  'rpe.1': 'Muy suave',
  'rpe.2': 'Suave',
  'rpe.3': 'Cómodo',
  'rpe.4': 'Algo exigente',
  'rpe.5': 'Moderado',
  'rpe.6': 'Exigente',
  'rpe.7': 'Duro',
  'rpe.8': 'Muy duro',
  'rpe.9': 'Casi máximo',
  'rpe.10': 'Máximo',
  'plan.borrarPregunta': '¿Borrar este entrenamiento?',
  'plan.vacio': 'Todavía no hay entrenamientos en el plan.',
  'plan.estaSemana': 'Esta semana',
  'plan.hecho': 'Hecho',
  'plan.deshacer': 'Deshacer',
  'plan.marcarHecho': 'Marcar hecho',
  'plan.ocultarFases': 'Ocultar fases',
  'plan.verFases': 'Ver {n} fases',
  'plan.descargarFit': 'Descargar .FIT',
  'plan.comoGarmin': '¿Cómo lo paso al Garmin?',
  'plan.ocultarMusculos': 'Ocultar músculos',
  'plan.verMusculos': 'Ver {n} músculos',
  'plan.copiar': 'Copiar',
  'plan.copiado': 'Copiado',
  'plan.editar': 'Editar',
  'plan.borrar': 'Borrar',
  'plan.garminAviso': 'No lo subas por la web de Garmin Connect: ahí solo se importan actividades ya hechas, y saldría como una ruta.',
  'plan.garmin1': '1. Conecta el reloj al computador con el cable USB.',
  'plan.garmin2': '2. Abre la unidad del reloj y entra a',
  'plan.garmin3': '3. Copia el .FIT ahí dentro y desconecta el reloj.',
  'plan.garmin4': '4. En el reloj: Entrenamiento → Entrenamientos.',
  'act.parciales': 'PARCIALES POR KM',
  'act.vacio': 'Todavía no hay actividades. Las que grabes aquí o subas a Strava aparecerán en esta lista.',
  'act.sinNombre': 'Actividad',
  'act.verStrava': 'Ver en Strava',
  'chat.noEnviado': 'No se pudo enviar. Inténtalo de nuevo.',
  'chat.cargando': 'Cargando…',
  'chat.vacio': 'Aún no hay mensajes con {nombre}. Escribe el primero.',
  'chat.pista': 'Mensaje para {nombre}',
  'chat.enviar': 'Enviar',
  'cuenta.guardando': 'Guardando…',
  'cuenta.guardado': 'Guardado.',
  'cuenta.noGuardado': 'No se pudo guardar.',
  'cuenta.nombre': 'Nombre',
  'cuenta.codigo': 'Código de entrenador',
  'cuenta.codigoPista': 'Pega aquí el código de tu coach',
  'cuenta.clave': 'Contraseña',
  'cuenta.claveDesc': 'Ponte una contraseña para entrar en el teléfono sin depender del correo.',
  'cuenta.clavePista': 'Nueva contraseña (mín. 6)',
  'cuenta.guardarClave': 'Guardar contraseña',
  'cuenta.claveGuardada': 'Contraseña guardada. Ya puedes entrar desde cualquier dispositivo.',
  'cuenta.zonas': 'Zonas de pulso',
  'cuenta.zonasDesc': 'Con esto la app te avisa si vas dentro de la zona que te pidió tu entrenador.',
  'cuenta.pulsoMax': 'Pulso máximo',
  'cuenta.pulsoReposo': 'Pulso en reposo',
  'cuenta.guardarZonas': 'Guardar zonas',
  'cuenta.zonasGuardadas': 'Zonas guardadas.',
  'cuenta.strava': 'Strava',
  'cuenta.stravaOk': 'Conectado (atleta {id}). Las carreras nuevas llegan solas.',
  'cuenta.desconectarStrava': 'Desconectar Strava',
  'cuenta.desconectarPregunta': '¿Desconectar Strava? Dejarán de llegar tus carreras automáticamente. Las que ya están guardadas se quedan.',
  'cuenta.desconectando': 'Desconectando…',
  'cuenta.stravaFuera': 'Strava desconectado.',
  'cuenta.noDesconectado': 'No se pudo desconectar.',
  'cuenta.conectarStrava': 'Conectar con Strava',
  'cuenta.sesion': 'Sesión',
  'cuenta.salir': 'Cerrar sesión',
  'push.titulo': 'Notificaciones',
  'push.noSoportado': 'Este navegador no admite notificaciones. En iPhone, primero añade MyCoachRuns a la pantalla de inicio y ábrela desde ahí.',
  'push.bloqueado': 'Las bloqueaste en este navegador. Actívalas desde los ajustes del sitio y vuelve aquí.',
  'push.off': 'Recibe un aviso cuando tu entrenador te asigne o cambie un entrenamiento.',
  'push.activar': 'Activar notificaciones',
  'push.on': 'Activas en este dispositivo.',
  'push.desactivar': 'Desactivar',
  'push.listo': 'Listo. Te avisaremos cuando tu entrenador cambie algo.',
  'push.faltaLlave': 'Falta configurar la llave de notificaciones en el servidor.',
  'push.noGuardado': 'No se pudo guardar la suscripción.',
  'form.fecha': 'Fecha',
  'form.tipo': 'Tipo',
  'form.tambienA': 'Asignar también a',
  'form.sinNombre': 'Sin nombre',
  'form.musculos': 'Músculos trabajados',
  'form.titulo': 'Título',
  'form.tituloPista': 'Ej. Series 6×800',
  'form.fases': 'Fases',
  'form.fasesDesc': 'El alumno las verá una a una mientras corre, con avisos al terminar cada una.',
  'form.notas': 'Notas',
  'form.notasPista': 'Sensaciones a buscar, material, terreno…',
  'form.guardarCambios': 'Guardar cambios',
  'form.asignar': 'Asignar',
  'form.tardo': 'El servidor tardó demasiado. Revisa la conexión e inténtalo otra vez.',
  'fase.calentamiento': 'Calentamiento',
  'fase.trabajo': 'Trabajo',
  'fase.recuperacion': 'Recuperación',
  'fase.enfriamiento': 'Enfriamiento',
  'fase.pausa': 'Pausa',
  'fase.subir': 'Subir',
  'fase.bajar': 'Bajar',
  'fase.duplicar': 'Duplicar',
  'fase.borrarPregunta': '¿Borrar la fase "{nombre}"?',
  'fase.anadir': 'Añadir',
  'fase.repeticiones': 'Repeticiones',
  'fase.nombre': 'Nombre',
  'fase.nombrePista': 'Ej. 200 fuertes',
  'fase.medirPor': 'Medir por',
  'fase.distancia': 'Distancia (km)',
  'fase.tiempo': 'Tiempo (min)',
  'fase.kilometros': 'Kilómetros',
  'fase.minutos': 'Minutos',
  'fase.ritmoRapido': 'Ritmo rápido',
  'fase.ritmoLento': 'Ritmo lento',
  'fase.zona': 'Zona de pulso (opcional)',
  'fase.sinZona': 'Sin zona objetivo',
  'fase.zona1': 'Zona 1 — Recuperación',
  'fase.zona2': 'Zona 2 — Aeróbico suave',
  'fase.zona3': 'Zona 3 — Aeróbico fuerte',
  'fase.zona4': 'Zona 4 — Umbral',
  'fase.zona5': 'Zona 5 — Máximo',
  'fase.nombreRecu': 'Nombre de la recuperación',
  'fase.troteSuave': 'Trote suave',
  'pegar.copiado': 'ENTRENAMIENTO COPIADO',
  'pegar.otraFecha': 'Pegar otra fecha',
  'pegar.quitarCopia': 'Quitar copia',
  'pegar.pegando': 'Pegando…',
  'pegar.enPlan': 'Pegar en el plan de {nombre}',
  'pegar.quitar': 'Quitar',
  'pegar.noPegado': 'No se pudo pegar.',
  'pegar.noPegadoRed': 'No se pudo pegar. Revisa la conexión.',
  'pegar.aviso': 'Tienes copiado {titulo}. Entra en un alumno para pegarlo en su plan.',
  'refr.actualizando': 'Actualizando…',
  'refr.suelta': 'Suelta para actualizar',
  'refr.tira': 'Tira para actualizar',
  'musc.marcados': 'Marcados:',
  'musc.toca': 'Toca los músculos en el dibujo o en la lista.',
  'img.creando': 'Creando la imagen…',
  'img.guardar': 'Guardar o compartir imagen',
  'img.noCreada': 'No se pudo crear la imagen.',
  'img.noGuardada': 'No se pudo guardar la imagen.',
  'img.crearFoto': 'Crear foto con mis datos',
  'img.creandoCorto': 'Creando imagen…',
  'img.guardarCorto': 'Guardar o compartir',
  'img.otraFoto': 'Otra foto',
  'img.manten': 'También puedes mantener pulsada la imagen para guardarla.',
  'avatar.subiendo': 'Subiendo…',
  'avatar.cambiar': 'Cambiar foto',
  'avatar.subir': 'Subir foto',
  'avatar.hecho': 'Foto actualizada.',
  'avatar.fallo': 'No se pudo subir la foto.',
  'zona.1': 'Recuperación',
  'zona.2': 'Aeróbico suave',
  'zona.3': 'Aeróbico fuerte',
  'zona.4': 'Umbral',
  'zona.5': 'Máximo',
  'rec.pasoAPaso': 'PASO A PASO',
  'rec.bloques': 'ENTRENAMIENTO · {n} BLOQUES',
  'rec.unBloque': 'ENTRENAMIENTO · 1 BLOQUE',
  'rec.nFases': 'ENTRENAMIENTO · {n} FASES',
  'rec.enZona': 'En zona',
  'rec.pulsoAlto': 'Pulso alto',
  'rec.pulsoBajo': 'Pulso bajo',
  'rec.tiempo': 'tiempo',
  'rec.zonaPpm': '· zona {n} {nombre}',
  'rec.precision': 'Precisión GPS: ±{m} m',
  'rec.senalDebil': '— señal débil, la distancia puede quedarse corta',
  'rec.avisosVoz': 'Avisos por voz y sonido en cada kilómetro',
  'rec.subirStrava': 'Subir también a Strava',
  'act.desnivel': 'm desnivel',
  'act.esfuerzo': 'Esfuerzo {n}/10',
  'musc.pecho': 'Pecho',
  'musc.hombros': 'Hombros',
  'musc.biceps': 'Bíceps',
  'musc.antebrazos': 'Antebrazos',
  'musc.abdomen': 'Abdominales',
  'musc.oblicuos': 'Oblicuos',
  'musc.cuadriceps': 'Cuádriceps',
  'musc.aductores': 'Aductores',
  'musc.tibial': 'Tibial',
  'musc.trapecio': 'Trapecio',
  'musc.dorsal': 'Dorsal',
  'musc.lumbar': 'Lumbar',
  'musc.triceps': 'Tríceps',
  'musc.gluteos': 'Glúteos',
  'musc.isquios': 'Isquiotibiales',
  'musc.gemelos': 'Gemelos',
  'img.fuerza': 'Fuerza',
  'desc.ritmo': ' a {a} /km',
  'desc.zona': ' · zona {n}',
  'desc.recu': ' · recuperación {cant}',
  'desc.parado': ' parado',
  'fase.pasos': '{n} pasos · {km} km · ~{min} min',
  'fase.anadirFase': '+ Añadir fase',
  'fase.recuEntre': 'Recuperación entre repeticiones',
  'fase.trotando': 'Trotando (si lo desmarcas, es parada completa)',
  'fase.trasUltima': 'Incluir también después de la última repetición',
  'pie.escribenos': 'Escríbenos',
  'pie.apoyar': 'Apoyar el proyecto',
  'pie.lema': 'MyCoachRuns · Entrena, mejora, avanza',
  'entrar.servidorDijo': 'El servidor respondió {n} al comprobar tu sesión.',
  'alumnos.sinNombre': 'Sin nombre',
  'plan.conectaStrava': 'Conecta Strava para que tus carreras se sincronicen solas.',
  'plan.conectar': 'Conectar',
  'plan.sinCoach': 'Todavía no estás vinculado a un entrenador. Pídele su enlace de invitación.',
  'chat.sinCargar': 'No se pudieron cargar los mensajes. Necesitan conexión.',
  'chat.sinCoach': 'Todavía no estás vinculado a un entrenador, así que no hay con quién conversar.',
  'chat.sinAlumnos': 'Aún no tienes alumnos.',
  'chat.sinLeer': '{n} sin leer',
  'chat.alDia': 'Al día',
  'alumno.stravaOk': 'Strava conectado',
  'alumno.sinStrava': 'Sin Strava',
  'alumno.asignar': 'Asignar entrenamiento',
} as const;
