/**
 * Français. Traducción de `es.ts`, que es la tabla de referencia.
 *
 * El tipo obliga a tenerlas todas: si se añade una frase en español y aquí
 * falta, TypeScript avisa al compilar en vez de dejar un hueco.
 */
import type { es } from './es';

export const fr: Record<keyof typeof es, string> = {
  // ---------------------------------------------------------- navegación
  'tab.alumnos': 'Athlètes',
  'tab.plan': 'Plan',
  'tab.actividades': 'Activités',
  'tab.iniciar': 'Démarrer',
  'tab.chat': 'Messages',
  'tab.cuenta': 'Compte',

  // ---------------------------------------------------------- cabeceras
  'alumnos.titulo': 'Athlètes',
  'alumnos.frase': 'Gère tes athlètes, crée leurs plans et fais progresser leur niveau.',
  'alumnos.enTrenamiento': 'À l’entraînement',
  'alumnos.sinPlan': 'Sans plan',
  'alumnos.vacio': 'Pas encore d’athlètes. Partage ton lien d’invitation.',
  'plan.titulo': 'Mon plan',
  'plan.frase': 'Ce qui est prévu cette semaine. Coche ce qui est fait et va courir.',
  'actividades.titulo': 'Activités',
  'actividades.frase': 'Tout ce que tu as couru, marché et travaillé.',
  'iniciar.titulo': 'Démarrer',
  'iniciar.frase': 'Enregistre ta séance avec le GPS. Il continue à mesurer écran éteint.',
  'chat.titulo': 'Messages',
  'chat.fraseCoach': 'Parle à tes athlètes, réponds à leurs questions et ajuste le plan.',
  'chat.fraseAtleta': 'Écris à ton entraîneur quand tu en as besoin.',
  'cuenta.titulo': 'Compte',
  'cuenta.frase': 'Ton profil, tes zones de fréquence cardiaque et la connexion Strava.',
  'servicios.titulo': 'Services',
  'servicios.frase': 'Un vrai accompagnement, dans l’appli et en dehors.',

  // ---------------------------------------------------------- invitar
  'invitar.titulo': 'Inviter des athlètes',
  'invitar.desc': 'Partage le lien et ajoute-les à ton groupe.',
  'invitar.copiar': 'Copier',
  'invitar.copiado': 'Copié',
  'invitar.compartir': 'Rejoins mon groupe d’entraînement sur MyCoachRuns : {link}',

  // ---------------------------------------------------------- entrar
  'entrar.lema': 'Ton entraîneur prépare le plan. Toi, tu vas courir.',
  'entrar.entrar': 'Se connecter',
  'entrar.crear': 'Créer un compte',
  'entrar.sinClave': 'Sans mot de passe',
  'entrar.correo': 'E-mail',
  'entrar.clave': 'Mot de passe',
  'entrar.clavePista': 'Au moins 6 caractères',
  'entrar.nombre': 'Nom',
  'entrar.nombrePista': 'Comment ton entraîneur t’appelle',
  'entrar.codigo': 'Code entraîneur (facultatif)',
  'entrar.codigoPista': 'Ton coach te le donne',
  'entrar.espera': 'Un instant…',
  'entrar.enviarEnlace': 'Envoyer le lien',
  'entrar.olvide': 'J’ai oublié mon mot de passe',
  'entrar.mandarCorreo': 'M’envoyer l’e-mail',
  'entrar.volverClave': 'Revenir à la connexion par mot de passe',
  'entrar.pocosCorreos': 'L’e-mail met deux ou trois minutes. On ne peut en envoyer que quelques-uns par heure.',
  'entrar.instalar': 'Pour l’installer : dans le navigateur, touche « Partager » → « Sur l’écran d’accueil ».',
  'entrar.invita': '{nombre} t’invite à t’entraîner. Crée ton compte et tu rejoindras son groupe.',
  'entrar.sesionRota': 'Ta session est restée à moitié ouverte. Reconnecte-toi avec ton e-mail et ton mot de passe.',
  'entrar.limpiar': 'Effacer la session',
  'entrar.noSesion': 'Impossible de vérifier ta session.',
  'entrar.malClave': 'E-mail ou mot de passe incorrect.',
  'entrar.muchosCorreos': 'Trop d’e-mails à la suite. Attends un peu ou connecte-toi avec un mot de passe.',
  'entrar.yaExiste': 'Il existe déjà un compte avec cet e-mail. Connecte-toi depuis l’onglet « Se connecter ».',
  'entrar.revisaCorreo': 'Compte créé. Regarde ta boîte mail pour le confirmer, puis connecte-toi avec ton mot de passe.',
  'entrar.enlaceEnviado': 'Nous t’avons envoyé un lien par e-mail.',
  'entrar.recuperaEnviado': 'Nous t’avons envoyé un e-mail. Ouvre-le depuis ce même téléphone et il t’emmènera choisir un nouveau mot de passe. S’il n’arrive pas au bout de quelques minutes, regarde dans les courriers indésirables.',

  // ---------------------------------------------------------- grabar
  'grabar.queHacer': 'TU VAS FAIRE QUOI ?',
  'grabar.comoHacer': 'COMMENT TU VAS LE FAIRE',
  'grabar.libre': 'Libre',
  'grabar.sinAsignar': 'Aucune séance prévue',
  'grabar.yaMarcado': 'déjà fait',
  'grabar.hoy': 'Aujourd’hui',
  'grabar.fases': '{n} phases',
  'grabar.correr': 'Course',
  'grabar.caminata': 'Marche',
  'grabar.trail': 'Trail',
  'grabar.enMarcha': 'En cours',
  'grabar.enPausa': 'En pause',
  'grabar.terminada': 'Terminée',
  'grabar.sinConexion': 'Hors ligne : voici la dernière chose enregistrée sur le téléphone.',

  // ---------------------------------------------------------- tipos
  'tipo.easy': 'Footing',
  'tipo.long': 'Sortie longue',
  'tipo.tempo': 'Tempo',
  'tipo.intervals': 'Fractionné',
  'tipo.trail': 'Trail',
  'tipo.walk': 'Marche',
  'tipo.race': 'Course',
  'tipo.strength': 'Renforcement',
  'tipo.rest': 'Repos',

  // ---------------------------------------------------------- servicios
  'serv.pacingTitulo': 'Lièvre en course · 5 à 10 km',
  'serv.pacingDesc': 'Je cours avec toi et je tiens l’allure convenue, pour que tu ne partes pas trop vite et que tu ne craques pas à la fin.',
  'serv.pacing1': 'Événements et courses populaires',
  'serv.pacing2': 'Groupes qui visent un même chrono',
  'serv.pacing3': 'Une seule personne, à ton allure cible',
  'serv.unoTitulo': 'Entraînement en individuel',
  'serv.unoDesc': 'Un plan fait pour toi et ajusté semaine après semaine selon ta réponse, pas un modèle identique pour tout le monde.',
  'serv.uno1': 'Séances structurées dans l’appli, avec annonces vocales',
  'serv.uno2': 'Suivi de tes sorties et de ton effort',
  'serv.uno3': 'Contact direct par la messagerie',
  'serv.precioTitulo': 'Combien ça coûte ?',
  'serv.precioDesc': 'Ça dépend de la distance, des dates et s’il s’agit d’une personne ou d’un groupe. Écris-moi et on en parle sans engagement : je te dis ce qui te correspond et combien ce serait.',
  'serv.whatsapp': 'Écris-moi sur WhatsApp',
  'serv.correo': 'Écris-moi par e-mail',
  'serv.saludoWa': 'Bonjour, je vous écris depuis MyCoachRuns. Vos services m’intéressent.',
  'serv.asuntoCorreo': 'Question sur les services de MyCoachRuns',

  // ---------------------------------------------------------- menú
  'menu.abrir': 'Ouvrir le menu',
  'menu.cerrar': 'Fermer',
  'menu.serviciosDesc': 'Lièvre en course et entraînement individuel',
  'menu.cuentaDesc': 'Ton profil, ta fréquence cardiaque et Strava',
  'menu.escribenos': 'Écris-nous',
  'menu.instagram': 'Instagram',
  'menu.strava': 'Strava',
  'menu.stravaDesc': 'Suivre le développeur',
  'menu.apoyar': 'Soutenir le projet',
  'menu.apoyarDesc': 'Offre-moi un café',

  // ---------------------------------------------------------- cuenta
  'cuenta.idioma': 'Langue',
  'cuenta.idiomaDesc': 'Change la langue de l’appli et des annonces vocales.',

  // ---------------------------------------------------------- comunes
  'com.guardar': 'Enregistrer',
  'com.cancelar': 'Annuler',
  'com.cerrar': 'Fermer',
  'com.actualizar': 'Mettre à jour',
  'com.reintentar': 'Réessayer',
  'com.sinRed': 'Impossible de joindre le serveur. Vérifie ta connexion.',
  'com.sinRedServidor': 'Impossible de joindre le serveur ({url}). Vérifie que le téléphone a internet.',
  'com.algoFallo': 'Quelque chose a échoué sans dire pourquoi.',
  'com.sesionCaducada': 'Ta session a expiré. Reconnecte-toi.',

  // ---------------------------------------------------------- voz
  'voz.empezamos': 'C’est parti.',
  'voz.alDia': 'À jour.',
  'voz.kilometro': 'Kilomètre {n}. Allure moyenne {ritmo} au kilomètre',
  'voz.pulsoMedio': ', fréquence cardiaque {ppm}',
  'voz.entreRitmos': ', à une allure entre {a} et {b} au kilomètre',
  'voz.unRitmo': ', à une allure de {a} au kilomètre',
  'voz.zonaPulso': ', en zone {n} de fréquence cardiaque',
  'voz.minutos': '{n} minutes',
  'voz.unMinuto': '1 minute',
  'voz.segundos': '{n} secondes',
  'voz.minutosYsegundos': '{m} et {s} secondes',
  'voz.metros': '{n} mètres',
  'voz.kilometros': '{n} kilomètres',
  'voz.coma': ' virgule ',
  'voz.de': ' sur ',
  'voz.horas': '{n} heures',
  'voz.unaHora': '1 heure',
  'voz.buenaCarrera': 'Bonne séance.',
  'voz.seguimos': 'On repart.',
  'voz.enPausa': 'En pause.',
  'voz.completado': 'Séance terminée. Beau travail.',
  'voz.terminada': 'Activité terminée. {dist} en {tiempo}.',

  // ------------------------------------------ el resto de la app
  'rec.verResumen': 'Voir le résumé',
  'rec.verRepes': 'Voir chaque répétition',
  'rec.saltarFase': 'Passer à la phase suivante',
  'rec.completado': 'Séance terminée.',
  'rec.completadoDesc': 'Tu peux continuer à courir ou appuyer sur Terminer.',
  'rec.sensor': 'Capteur : {n}',
  'rec.conectarPulso': 'Connecter la ceinture cardio',
  'rec.iniciarEntreno': 'Démarrer la séance ({n} phases)',
  'rec.iniciarLibre': 'Démarrer une sortie libre',
  'rec.pausar': 'Pause',
  'rec.continuar': 'Reprendre',
  'rec.terminar': 'Terminer',
  'rec.comoSintio': 'Tu l’as senti comment ?',
  'rec.rpeVacio': 'Effort ressenti (facultatif)',
  'rec.notasPista': 'Notes pour ton entraîneur (facultatif)',
  'rec.guardarStrava': 'Enregistrer et envoyer sur Strava',
  'rec.guardarSolo': 'Enregistrer seulement dans MyCoachRuns',
  'rec.descartarPregunta': 'Supprimer cette sortie ? Elle sera perdue.',
  'rec.descartar': 'Supprimer',
  'rec.guardando': 'Enregistrement…',
  'rec.verActividades': 'Voir mes activités',
  'rec.grabarOtra': 'En enregistrer une autre',
  'rec.sinGps': 'Ce navigateur n’a pas de GPS.',
  'rpe.1': 'Très facile',
  'rpe.2': 'Facile',
  'rpe.3': 'Confortable',
  'rpe.4': 'Un peu exigeant',
  'rpe.5': 'Modéré',
  'rpe.6': 'Exigeant',
  'rpe.7': 'Dur',
  'rpe.8': 'Très dur',
  'rpe.9': 'Presque maximal',
  'rpe.10': 'Maximal',
  'plan.borrarPregunta': 'Supprimer cette séance ?',
  'plan.vacio': 'Il n’y a pas encore de séances dans le plan.',
  'plan.estaSemana': 'Cette semaine',
  'plan.hecho': 'Fait',
  'plan.deshacer': 'Annuler',
  'plan.marcarHecho': 'Marquer comme fait',
  'plan.ocultarFases': 'Masquer les phases',
  'plan.verFases': 'Voir {n} phases',
  'plan.descargarFit': 'Télécharger le .FIT',
  'plan.comoGarmin': 'Comment le mettre sur la Garmin ?',
  'plan.ocultarMusculos': 'Masquer les muscles',
  'plan.verMusculos': 'Voir {n} muscles',
  'plan.copiar': 'Copier',
  'plan.copiado': 'Copié',
  'plan.editar': 'Modifier',
  'plan.borrar': 'Supprimer',
  'plan.garminAviso': 'Ne le charge pas depuis le site Garmin Connect : là-bas on n’importe que des activités déjà faites, et il apparaîtrait comme un parcours.',
  'plan.garmin1': '1. Branche la montre à l’ordinateur avec le câble USB.',
  'plan.garmin2': '2. Ouvre le lecteur de la montre et va dans',
  'plan.garmin3': '3. Copie le .FIT dedans et débranche la montre.',
  'plan.garmin4': '4. Sur la montre : Entraînement → Entraînements.',
  'act.parciales': 'TEMPS AU KM',
  'act.vacio': 'Pas encore d’activités. Celles que tu enregistres ici ou que tu envoies sur Strava apparaîtront dans cette liste.',
  'act.sinNombre': 'Activité',
  'act.verStrava': 'Voir sur Strava',
  'chat.noEnviado': 'Envoi impossible. Réessaie.',
  'chat.cargando': 'Chargement…',
  'chat.vacio': 'Pas encore de messages avec {nombre}. Écris le premier.',
  'chat.pista': 'Message pour {nombre}',
  'chat.enviar': 'Envoyer',
  'cuenta.guardando': 'Enregistrement…',
  'cuenta.guardado': 'Enregistré.',
  'cuenta.noGuardado': 'Enregistrement impossible.',
  'cuenta.nombre': 'Nom',
  'cuenta.codigo': 'Code entraîneur',
  'cuenta.codigoPista': 'Colle ici le code de ton coach',
  'cuenta.clave': 'Mot de passe',
  'cuenta.claveDesc': 'Choisis un mot de passe pour te connecter sur le téléphone sans dépendre de l’e-mail.',
  'cuenta.clavePista': 'Nouveau mot de passe (min. 6)',
  'cuenta.guardarClave': 'Enregistrer le mot de passe',
  'cuenta.claveGuardada': 'Mot de passe enregistré. Tu peux maintenant te connecter depuis n’importe quel appareil.',
  'cuenta.zonas': 'Zones de fréquence cardiaque',
  'cuenta.zonasDesc': 'Avec ça, l’appli te dit si tu es dans la zone demandée par ton entraîneur.',
  'cuenta.pulsoMax': 'Fréquence cardiaque max',
  'cuenta.pulsoReposo': 'Fréquence cardiaque au repos',
  'cuenta.guardarZonas': 'Enregistrer les zones',
  'cuenta.zonasGuardadas': 'Zones enregistrées.',
  'cuenta.strava': 'Strava',
  'cuenta.stravaOk': 'Connecté (athlète {id}). Les nouvelles sorties arrivent toutes seules.',
  'cuenta.desconectarStrava': 'Déconnecter Strava',
  'cuenta.desconectarPregunta': 'Déconnecter Strava ? Tes sorties n’arriveront plus toutes seules. Celles déjà enregistrées restent.',
  'cuenta.desconectando': 'Déconnexion…',
  'cuenta.stravaFuera': 'Strava déconnecté.',
  'cuenta.noDesconectado': 'Déconnexion impossible.',
  'cuenta.conectarStrava': 'Se connecter à Strava',
  'cuenta.sesion': 'Session',
  'cuenta.salir': 'Se déconnecter',
  'push.titulo': 'Notifications',
  'push.noSoportado': 'Ce navigateur ne gère pas les notifications. Sur iPhone, ajoute d’abord MyCoachRuns à l’écran d’accueil et ouvre-la de là.',
  'push.bloqueado': 'Tu les as bloquées dans ce navigateur. Active-les dans les réglages du site et reviens ici.',
  'push.off': 'Reçois un avis quand ton entraîneur te met ou modifie une séance.',
  'push.activar': 'Activer les notifications',
  'push.on': 'Activées sur cet appareil.',
  'push.desactivar': 'Désactiver',
  'push.listo': 'C’est bon. On te préviendra quand ton entraîneur changera quelque chose.',
  'push.faltaLlave': 'La clé des notifications n’est pas configurée sur le serveur.',
  'push.noGuardado': 'Impossible d’enregistrer l’abonnement.',
  'form.fecha': 'Date',
  'form.tipo': 'Type',
  'form.tambienA': 'Attribuer aussi à',
  'form.sinNombre': 'Sans nom',
  'form.musculos': 'Muscles travaillés',
  'form.titulo': 'Titre',
  'form.tituloPista': 'Ex. 6×800 fractionné',
  'form.fases': 'Phases',
  'form.fasesDesc': 'L’athlète les voit une par une en courant, avec une annonce à la fin de chacune.',
  'form.notas': 'Notes',
  'form.notasPista': 'Sensations à chercher, matériel, terrain…',
  'form.guardarCambios': 'Enregistrer les modifications',
  'form.asignar': 'Attribuer',
  'form.tardo': 'Le serveur a mis trop de temps. Vérifie la connexion et réessaie.',
  'fase.calentamiento': 'Échauffement',
  'fase.trabajo': 'Travail',
  'fase.recuperacion': 'Récupération',
  'fase.enfriamiento': 'Retour au calme',
  'fase.pausa': 'Arrêt',
  'fase.subir': 'Monter',
  'fase.bajar': 'Descendre',
  'fase.duplicar': 'Dupliquer',
  'fase.borrarPregunta': 'Supprimer la phase « {nombre} » ?',
  'fase.anadir': 'Ajouter',
  'fase.repeticiones': 'Répétitions',
  'fase.nombre': 'Nom',
  'fase.nombrePista': 'Ex. 200 rapides',
  'fase.medirPor': 'Mesurer en',
  'fase.distancia': 'Distance (km)',
  'fase.tiempo': 'Temps (min)',
  'fase.kilometros': 'Kilomètres',
  'fase.minutos': 'Minutes',
  'fase.ritmoRapido': 'Allure rapide',
  'fase.ritmoLento': 'Allure lente',
  'fase.zona': 'Zone cardiaque (facultatif)',
  'fase.sinZona': 'Pas de zone cible',
  'fase.zona1': 'Zone 1 — Récupération',
  'fase.zona2': 'Zone 2 — Aérobie légère',
  'fase.zona3': 'Zone 3 — Aérobie soutenue',
  'fase.zona4': 'Zone 4 — Seuil',
  'fase.zona5': 'Zone 5 — Maximum',
  'fase.nombreRecu': 'Nom de la récupération',
  'fase.troteSuave': 'Footing léger',
  'pegar.copiado': 'SÉANCE COPIÉE',
  'pegar.otraFecha': 'Coller à une autre date',
  'pegar.quitarCopia': 'Retirer la copie',
  'pegar.pegando': 'Collage…',
  'pegar.enPlan': 'Coller dans le plan de {nombre}',
  'pegar.quitar': 'Retirer',
  'pegar.noPegado': 'Collage impossible.',
  'pegar.noPegadoRed': 'Collage impossible. Vérifie la connexion.',
  'pegar.aviso': 'Tu as copié {titulo}. Ouvre un athlète pour le coller dans son plan.',
  'refr.actualizando': 'Actualisation…',
  'refr.suelta': 'Relâche pour actualiser',
  'refr.tira': 'Tire pour actualiser',
  'musc.marcados': 'Sélectionnés :',
  'musc.toca': 'Touche les muscles sur le dessin ou dans la liste.',
  'img.creando': 'Création de l’image…',
  'img.guardar': 'Enregistrer ou partager l’image',
  'img.noCreada': 'Impossible de créer l’image.',
  'img.noGuardada': 'Impossible d’enregistrer l’image.',
  'img.crearFoto': 'Créer une photo avec mes données',
  'img.creandoCorto': 'Création de l’image…',
  'img.guardarCorto': 'Enregistrer ou partager',
  'img.otraFoto': 'Une autre photo',
  'img.manten': 'Tu peux aussi appuyer longuement sur l’image pour l’enregistrer.',
  'avatar.subiendo': 'Envoi…',
  'avatar.cambiar': 'Changer la photo',
  'avatar.subir': 'Envoyer une photo',
  'avatar.hecho': 'Photo mise à jour.',
  'avatar.fallo': 'Impossible d’envoyer la photo.',
  'zona.1': 'Récupération',
  'zona.2': 'Aérobie légère',
  'zona.3': 'Aérobie soutenue',
  'zona.4': 'Seuil',
  'zona.5': 'Maximum',
  'rec.pasoAPaso': 'PAS À PAS',
  'rec.bloques': 'SÉANCE · {n} BLOCS',
  'rec.unBloque': 'SÉANCE · 1 BLOC',
  'rec.nFases': 'SÉANCE · {n} PHASES',
  'rec.enZona': 'Dans la zone',
  'rec.pulsoAlto': 'Pouls trop haut',
  'rec.pulsoBajo': 'Pouls trop bas',
  'rec.tiempo': 'temps',
  'rec.zonaPpm': '· zone {n} {nombre}',
  'rec.precision': 'Précision GPS : ±{m} m',
  'rec.senalDebil': '— signal faible, la distance peut être sous-estimée',
  'rec.avisosVoz': 'Annonces vocales et sonores à chaque kilomètre',
  'rec.subirStrava': 'Envoyer aussi sur Strava',
  'act.desnivel': 'm de dénivelé',
  'act.esfuerzo': 'Effort {n}/10',
  'musc.pecho': 'Pectoraux',
  'musc.hombros': 'Épaules',
  'musc.biceps': 'Biceps',
  'musc.antebrazos': 'Avant-bras',
  'musc.abdomen': 'Abdominaux',
  'musc.oblicuos': 'Obliques',
  'musc.cuadriceps': 'Quadriceps',
  'musc.aductores': 'Adducteurs',
  'musc.tibial': 'Jambier',
  'musc.trapecio': 'Trapèzes',
  'musc.dorsal': 'Grand dorsal',
  'musc.lumbar': 'Lombaires',
  'musc.triceps': 'Triceps',
  'musc.gluteos': 'Fessiers',
  'musc.isquios': 'Ischio-jambiers',
  'musc.gemelos': 'Mollets',
  'img.fuerza': 'Renforcement',
  'desc.ritmo': ' à {a} /km',
  'desc.zona': ' · zone {n}',
  'desc.recu': ' · récupération {cant}',
  'desc.parado': ' à l’arrêt',
  'fase.pasos': '{n} étapes · {km} km · ~{min} min',
  'fase.anadirFase': '+ Ajouter une phase',
  'fase.recuEntre': 'Récupération entre les répétitions',
  'fase.trotando': 'En trottinant (décoche pour un arrêt complet)',
  'fase.trasUltima': 'L’inclure aussi après la dernière répétition',
  'pie.escribenos': 'Écris-nous',
  'pie.apoyar': 'Soutenir le projet',
  'pie.lema': 'MyCoachRuns · Entraîne-toi, progresse, avance',
  'entrar.servidorDijo': 'Le serveur a répondu {n} en vérifiant ta session.',
  'alumnos.sinNombre': 'Sans nom',
  'plan.conectaStrava': 'Connecte Strava pour que tes sorties se synchronisent toutes seules.',
  'plan.conectar': 'Connecter',
  'plan.sinCoach': 'Tu n’es pas encore relié à un entraîneur. Demande-lui son lien d’invitation.',
  'chat.sinCargar': 'Impossible de charger les messages. Il faut une connexion.',
  'chat.sinCoach': 'Tu n’es pas encore relié à un entraîneur, il n’y a donc personne à qui parler.',
  'chat.sinAlumnos': 'Tu n’as pas encore d’athlètes.',
  'chat.sinLeer': '{n} non lus',
  'chat.alDia': 'À jour',
  'alumno.stravaOk': 'Strava connecté',
  'alumno.sinStrava': 'Sans Strava',
  'alumno.asignar': 'Attribuer une séance',
} as const;
