/**
 * Português (Brasil). Traducción de `es.ts`, que es la tabla de referencia.
 *
 * El tipo obliga a tenerlas todas: si se añade una frase en español y aquí
 * falta, TypeScript avisa al compilar en vez de dejar un hueco.
 */
import type { es } from './es';

export const pt: Record<keyof typeof es, string> = {
  // ---------------------------------------------------------- navegación
  'tab.alumnos': 'Atletas',
  'tab.plan': 'Plano',
  'tab.actividades': 'Atividades',
  'tab.iniciar': 'Iniciar',
  'tab.chat': 'Mensagens',
  'tab.cuenta': 'Conta',

  // ---------------------------------------------------------- cabeceras
  'alumnos.titulo': 'Atletas',
  'alumnos.frase': 'Cuide dos seus atletas, monte os planos e leve o progresso deles adiante.',
  'alumnos.enTrenamiento': 'Em treino',
  'alumnos.sinPlan': 'Sem plano',
  'alumnos.vacio': 'Ainda não há atletas. Compartilhe seu link de convite.',
  'plan.titulo': 'Meu plano',
  'plan.frase': 'O que tem para esta semana. Marque o que fez e vá correr.',
  'actividades.titulo': 'Atividades',
  'actividades.frase': 'Tudo o que você correu, caminhou e treinou.',
  'iniciar.titulo': 'Iniciar',
  'iniciar.frase': 'Grave sua sessão com GPS. Continua medindo com a tela apagada.',
  'chat.titulo': 'Mensagens',
  'chat.fraseCoach': 'Fale com seus atletas, tire dúvidas e ajuste o plano.',
  'chat.fraseAtleta': 'Escreva para o seu treinador quando precisar.',
  'cuenta.titulo': 'Conta',
  'cuenta.frase': 'Seu perfil, suas zonas de frequência cardíaca e a conexão com o Strava.',
  'servicios.titulo': 'Serviços',
  'servicios.frase': 'Acompanhamento de verdade, dentro e fora do aplicativo.',

  // ---------------------------------------------------------- invitar
  'invitar.titulo': 'Convidar atletas',
  'invitar.desc': 'Compartilhe o link e some eles ao seu grupo.',
  'invitar.copiar': 'Copiar',
  'invitar.copiado': 'Copiado',
  'invitar.compartir': 'Entre no meu grupo de treino no MyCoachRuns: {link}',

  // ---------------------------------------------------------- entrar
  'entrar.lema': 'Seu treinador monta o plano. Você sai para correr.',
  'entrar.entrar': 'Entrar',
  'entrar.crear': 'Criar conta',
  'entrar.sinClave': 'Sem senha',
  'entrar.correo': 'E-mail',
  'entrar.clave': 'Senha',
  'entrar.clavePista': 'No mínimo 6 caracteres',
  'entrar.nombre': 'Nome',
  'entrar.nombrePista': 'Como o seu treinador te chama',
  'entrar.codigo': 'Código do treinador (opcional)',
  'entrar.codigoPista': 'Seu coach te passa',
  'entrar.espera': 'Um momento…',
  'entrar.enviarEnlace': 'Enviar link',
  'entrar.olvide': 'Esqueci minha senha',
  'entrar.mandarCorreo': 'Me mandar o e-mail',
  'entrar.volverClave': 'Voltar a entrar com senha',
  'entrar.pocosCorreos': 'O e-mail demora uns minutos. Só dá para mandar alguns por hora.',
  'entrar.instalar': 'Para instalar: no navegador toque em «Compartilhar» → «Adicionar à tela de início».',
  'entrar.invita': '{nombre} está te convidando para treinar. Crie sua conta e você entra no grupo.',
  'entrar.sesionRota': 'Sua sessão ficou pela metade. Entre de novo com seu e-mail e sua senha.',
  'entrar.limpiar': 'Limpar sessão',
  'entrar.noSesion': 'Não foi possível verificar sua sessão.',
  'entrar.malClave': 'E-mail ou senha incorretos.',
  'entrar.muchosCorreos': 'Muitos e-mails seguidos. Espere um pouco ou entre com senha.',
  'entrar.yaExiste': 'Já existe uma conta com esse e-mail. Entre pela aba «Entrar».',
  'entrar.revisaCorreo': 'Conta criada. Veja seu e-mail para confirmar e depois entre com sua senha.',
  'entrar.enlaceEnviado': 'Enviamos um link para o seu e-mail.',
  'entrar.recuperaEnviado': 'Mandamos um e-mail. Abra pelo mesmo celular e ele vai te levar a escolher uma senha nova. Se não chegar em alguns minutos, olhe na caixa de spam.',

  // ---------------------------------------------------------- grabar
  'grabar.queHacer': 'O QUE VOCÊ VAI FAZER?',
  'grabar.comoHacer': 'COMO VOCÊ VAI FAZER',
  'grabar.libre': 'Livre',
  'grabar.sinAsignar': 'Sem treino atribuído',
  'grabar.yaMarcado': 'já feito',
  'grabar.hoy': 'Hoje',
  'grabar.fases': '{n} fases',
  'grabar.correr': 'Corrida',
  'grabar.caminata': 'Caminhada',
  'grabar.trail': 'Trail',
  'grabar.enMarcha': 'Em andamento',
  'grabar.enPausa': 'Em pausa',
  'grabar.terminada': 'Terminada',
  'grabar.sinConexion': 'Sem conexão: isto é o último que ficou salvo no celular.',

  // ---------------------------------------------------------- tipos
  'tipo.easy': 'Rodagem leve',
  'tipo.long': 'Longão',
  'tipo.tempo': 'Tempo',
  'tipo.intervals': 'Tiros',
  'tipo.trail': 'Trail',
  'tipo.walk': 'Caminhada',
  'tipo.race': 'Prova',
  'tipo.strength': 'Força',
  'tipo.rest': 'Descanso',

  // ---------------------------------------------------------- servicios
  'serv.pacingTitulo': 'Pacer em prova · 5K a 10K',
  'serv.pacingDesc': 'Eu corro com você e seguro o ritmo combinado, para você não sair rápido demais nem cair no final.',
  'serv.pacing1': 'Eventos e corridas de rua',
  'serv.pacing2': 'Grupos atrás de um tempo em comum',
  'serv.pacing3': 'Uma pessoa só, no seu ritmo alvo',
  'serv.unoTitulo': 'Treinamento 1 a 1',
  'serv.unoDesc': 'Um plano feito para você e ajustado semana a semana conforme a sua resposta, não um modelo igual para todo mundo.',
  'serv.uno1': 'Sessões estruturadas no aplicativo, com avisos por voz',
  'serv.uno2': 'Acompanhamento das suas corridas e do seu esforço',
  'serv.uno3': 'Contato direto pelo chat',
  'serv.precioTitulo': 'Quanto custa?',
  'serv.precioDesc': 'Depende da distância, das datas e de ser para uma pessoa ou um grupo. Me escreva e conversamos sem compromisso: eu digo o que combina com você e quanto ficaria.',
  'serv.whatsapp': 'Me chame no WhatsApp',
  'serv.correo': 'Me escreva por e-mail',
  'serv.saludoWa': 'Oi, estou escrevendo pelo MyCoachRuns. Tenho interesse nos seus serviços.',
  'serv.asuntoCorreo': 'Dúvida sobre os serviços do MyCoachRuns',

  // ---------------------------------------------------------- menú
  'menu.abrir': 'Abrir menu',
  'menu.cerrar': 'Fechar',
  'menu.serviciosDesc': 'Pacer em prova e treinamento 1 a 1',
  'menu.cuentaDesc': 'Seu perfil, frequência cardíaca e Strava',
  'menu.escribenos': 'Fale com a gente',
  'menu.instagram': 'Instagram',
  'menu.strava': 'Strava',
  'menu.stravaDesc': 'Siga o desenvolvedor',
  'menu.apoyar': 'Apoiar o projeto',
  'menu.apoyarDesc': 'Me pague um café',

  // ---------------------------------------------------------- cuenta
  'cuenta.idioma': 'Idioma',
  'cuenta.idiomaDesc': 'Muda o idioma do aplicativo e dos avisos por voz.',

  // ---------------------------------------------------------- comunes
  'com.guardar': 'Salvar',
  'com.cancelar': 'Cancelar',
  'com.cerrar': 'Fechar',
  'com.actualizar': 'Atualizar',
  'com.reintentar': 'Tentar de novo',
  'com.sinRed': 'Não foi possível falar com o servidor. Verifique sua conexão.',
  'com.sinRedServidor': 'Não foi possível falar com o servidor ({url}). Veja se o celular está com internet.',
  'com.algoFallo': 'Algo falhou e não disse por quê.',
  'com.sesionCaducada': 'Sua sessão expirou. Entre de novo.',

  // ---------------------------------------------------------- voz
  'voz.empezamos': 'Vamos lá.',
  'voz.alDia': 'Em dia.',
  'voz.kilometro': 'Quilômetro {n}. Ritmo médio {ritmo} por quilômetro',
  'voz.pulsoMedio': ', frequência cardíaca {ppm}',
  'voz.entreRitmos': ', em ritmo entre {a} e {b} por quilômetro',
  'voz.unRitmo': ', em ritmo de {a} por quilômetro',
  'voz.zonaPulso': ', na zona {n} de frequência cardíaca',
  'voz.minutos': '{n} minutos',
  'voz.unMinuto': '1 minuto',
  'voz.segundos': '{n} segundos',
  'voz.minutosYsegundos': '{m} e {s} segundos',
  'voz.metros': '{n} metros',
  'voz.kilometros': '{n} quilômetros',
  'voz.coma': ' vírgula ',
  'voz.de': ' de ',
  'voz.horas': '{n} horas',
  'voz.unaHora': '1 hora',
  'voz.buenaCarrera': 'Bom treino.',
  'voz.seguimos': 'Seguindo.',
  'voz.enPausa': 'Em pausa.',
  'voz.completado': 'Treino concluído. Bom trabalho.',
  'voz.terminada': 'Atividade terminada. {dist} em {tiempo}.',

  // ------------------------------------------ el resto de la app
  'rec.verResumen': 'Ver resumo',
  'rec.verRepes': 'Ver cada repetição',
  'rec.saltarFase': 'Pular para a próxima fase',
  'rec.completado': 'Treino concluído.',
  'rec.completadoDesc': 'Você pode continuar correndo ou tocar em Terminar.',
  'rec.sensor': 'Sensor: {n}',
  'rec.conectarPulso': 'Conectar cinta de frequência cardíaca',
  'rec.iniciarEntreno': 'Iniciar treino ({n} fases)',
  'rec.iniciarLibre': 'Iniciar corrida livre',
  'rec.pausar': 'Pausar',
  'rec.continuar': 'Continuar',
  'rec.terminar': 'Terminar',
  'rec.comoSintio': 'Como foi a sensação?',
  'rec.rpeVacio': 'Esforço percebido (opcional)',
  'rec.notasPista': 'Observações para o seu treinador (opcional)',
  'rec.guardarStrava': 'Salvar e enviar para o Strava',
  'rec.guardarSolo': 'Salvar só no MyCoachRuns',
  'rec.descartarPregunta': 'Descartar esta corrida? Não dá para recuperar.',
  'rec.descartar': 'Descartar',
  'rec.guardando': 'Salvando…',
  'rec.verActividades': 'Ver minhas atividades',
  'rec.grabarOtra': 'Gravar outra',
  'rec.sinGps': 'Este navegador não tem GPS.',
  'rpe.1': 'Muito leve',
  'rpe.2': 'Leve',
  'rpe.3': 'Confortável',
  'rpe.4': 'Um pouco puxado',
  'rpe.5': 'Moderado',
  'rpe.6': 'Puxado',
  'rpe.7': 'Difícil',
  'rpe.8': 'Muito difícil',
  'rpe.9': 'Quase máximo',
  'rpe.10': 'Máximo',
  'plan.borrarPregunta': 'Apagar este treino?',
  'plan.vacio': 'Ainda não há treinos no plano.',
  'plan.estaSemana': 'Esta semana',
  'plan.hecho': 'Feito',
  'plan.deshacer': 'Desfazer',
  'plan.marcarHecho': 'Marcar como feito',
  'plan.ocultarFases': 'Ocultar fases',
  'plan.verFases': 'Ver {n} fases',
  'plan.descargarFit': 'Baixar .FIT',
  'plan.comoGarmin': 'Como passo para o Garmin?',
  'plan.ocultarMusculos': 'Ocultar músculos',
  'plan.verMusculos': 'Ver {n} músculos',
  'plan.copiar': 'Copiar',
  'plan.copiado': 'Copiado',
  'plan.editar': 'Editar',
  'plan.borrar': 'Apagar',
  'plan.garminAviso': 'Não suba pelo site do Garmin Connect: lá só entram atividades já feitas, e ele apareceria como uma rota.',
  'plan.garmin1': '1. Conecte o relógio ao computador com o cabo USB.',
  'plan.garmin2': '2. Abra a unidade do relógio e entre em',
  'plan.garmin3': '3. Copie o .FIT ali dentro e desconecte o relógio.',
  'plan.garmin4': '4. No relógio: Treino → Treinos.',
  'act.parciales': 'PARCIAIS POR KM',
  'act.vacio': 'Ainda não há atividades. As que você gravar aqui ou subir para o Strava vão aparecer nesta lista.',
  'act.sinNombre': 'Atividade',
  'act.verStrava': 'Ver no Strava',
  'chat.noEnviado': 'Não deu para enviar. Tente de novo.',
  'chat.cargando': 'Carregando…',
  'chat.vacio': 'Ainda não há mensagens com {nombre}. Escreva a primeira.',
  'chat.pista': 'Mensagem para {nombre}',
  'chat.enviar': 'Enviar',
  'cuenta.guardando': 'Salvando…',
  'cuenta.guardado': 'Salvo.',
  'cuenta.noGuardado': 'Não deu para salvar.',
  'cuenta.nombre': 'Nome',
  'cuenta.codigo': 'Código do treinador',
  'cuenta.codigoPista': 'Cole aqui o código do seu coach',
  'cuenta.clave': 'Senha',
  'cuenta.claveDesc': 'Escolha uma senha para entrar no celular sem depender do e-mail.',
  'cuenta.clavePista': 'Nova senha (mín. 6)',
  'cuenta.guardarClave': 'Salvar senha',
  'cuenta.claveGuardada': 'Senha salva. Já dá para entrar de qualquer aparelho.',
  'cuenta.zonas': 'Zonas de frequência cardíaca',
  'cuenta.zonasDesc': 'Com isso o app avisa se você está dentro da zona que o treinador pediu.',
  'cuenta.pulsoMax': 'Frequência cardíaca máxima',
  'cuenta.pulsoReposo': 'Frequência cardíaca de repouso',
  'cuenta.guardarZonas': 'Salvar zonas',
  'cuenta.zonasGuardadas': 'Zonas salvas.',
  'cuenta.strava': 'Strava',
  'cuenta.stravaOk': 'Conectado (atleta {id}). As corridas novas chegam sozinhas.',
  'cuenta.desconectarStrava': 'Desconectar o Strava',
  'cuenta.desconectarPregunta': 'Desconectar o Strava? Suas corridas param de chegar sozinhas. As que já estão salvas ficam.',
  'cuenta.desconectando': 'Desconectando…',
  'cuenta.stravaFuera': 'Strava desconectado.',
  'cuenta.noDesconectado': 'Não deu para desconectar.',
  'cuenta.conectarStrava': 'Conectar com o Strava',
  'cuenta.sesion': 'Sessão',
  'cuenta.salir': 'Sair',
  'push.titulo': 'Notificações',
  'push.noSoportado': 'Este navegador não aceita notificações. No iPhone, primeiro adicione o MyCoachRuns à tela de início e abra por ali.',
  'push.bloqueado': 'Você bloqueou neste navegador. Ative nas configurações do site e volte aqui.',
  'push.off': 'Receba um aviso quando o treinador marcar ou mudar um treino.',
  'push.activar': 'Ativar notificações',
  'push.on': 'Ativadas neste aparelho.',
  'push.desactivar': 'Desativar',
  'push.listo': 'Pronto. A gente avisa quando o treinador mudar algo.',
  'push.faltaLlave': 'Falta configurar a chave de notificações no servidor.',
  'push.noGuardado': 'Não deu para salvar a inscrição.',
  'form.fecha': 'Data',
  'form.tipo': 'Tipo',
  'form.tambienA': 'Atribuir também a',
  'form.sinNombre': 'Sem nome',
  'form.musculos': 'Músculos trabalhados',
  'form.titulo': 'Título',
  'form.tituloPista': 'Ex. Tiros 6×800',
  'form.fases': 'Fases',
  'form.fasesDesc': 'O atleta vê uma por uma enquanto corre, com aviso no fim de cada uma.',
  'form.notas': 'Observações',
  'form.notasPista': 'Sensações a buscar, material, terreno…',
  'form.guardarCambios': 'Salvar alterações',
  'form.asignar': 'Atribuir',
  'form.tardo': 'O servidor demorou demais. Veja a conexão e tente de novo.',
  'fase.calentamiento': 'Aquecimento',
  'fase.trabajo': 'Trabalho',
  'fase.recuperacion': 'Recuperação',
  'fase.enfriamiento': 'Desaquecimento',
  'fase.pausa': 'Parada',
  'fase.subir': 'Subir',
  'fase.bajar': 'Descer',
  'fase.duplicar': 'Duplicar',
  'fase.borrarPregunta': 'Apagar a fase "{nombre}"?',
  'fase.anadir': 'Adicionar',
  'fase.repeticiones': 'Repetições',
  'fase.nombre': 'Nome',
  'fase.nombrePista': 'Ex. 200 fortes',
  'fase.medirPor': 'Medir por',
  'fase.distancia': 'Distância (km)',
  'fase.tiempo': 'Tempo (min)',
  'fase.kilometros': 'Quilômetros',
  'fase.minutos': 'Minutos',
  'fase.ritmoRapido': 'Ritmo rápido',
  'fase.ritmoLento': 'Ritmo lento',
  'fase.zona': 'Zona de frequência (opcional)',
  'fase.sinZona': 'Sem zona alvo',
  'fase.zona1': 'Zona 1 — Recuperação',
  'fase.zona2': 'Zona 2 — Aeróbico leve',
  'fase.zona3': 'Zona 3 — Aeróbico forte',
  'fase.zona4': 'Zona 4 — Limiar',
  'fase.zona5': 'Zona 5 — Máximo',
  'fase.nombreRecu': 'Nome da recuperação',
  'fase.troteSuave': 'Trote leve',
  'pegar.copiado': 'TREINO COPIADO',
  'pegar.otraFecha': 'Colar em outra data',
  'pegar.quitarCopia': 'Remover a cópia',
  'pegar.pegando': 'Colando…',
  'pegar.enPlan': 'Colar no plano de {nombre}',
  'pegar.quitar': 'Remover',
  'pegar.noPegado': 'Não deu para colar.',
  'pegar.noPegadoRed': 'Não deu para colar. Veja a conexão.',
  'pegar.aviso': 'Você copiou {titulo}. Abra um atleta para colar no plano dele.',
  'refr.actualizando': 'Atualizando…',
  'refr.suelta': 'Solte para atualizar',
  'refr.tira': 'Puxe para atualizar',
  'musc.marcados': 'Marcados:',
  'musc.toca': 'Toque nos músculos no desenho ou na lista.',
  'img.creando': 'Criando a imagem…',
  'img.guardar': 'Salvar ou compartilhar imagem',
  'img.noCreada': 'Não deu para criar a imagem.',
  'img.noGuardada': 'Não deu para salvar a imagem.',
  'img.crearFoto': 'Criar foto com os meus dados',
  'img.creandoCorto': 'Criando imagem…',
  'img.guardarCorto': 'Salvar ou compartilhar',
  'img.otraFoto': 'Outra foto',
  'img.manten': 'Você também pode segurar a imagem para salvá-la.',
  'avatar.subiendo': 'Enviando…',
  'avatar.cambiar': 'Trocar a foto',
  'avatar.subir': 'Enviar foto',
  'avatar.hecho': 'Foto atualizada.',
  'avatar.fallo': 'Não deu para enviar a foto.',
  'zona.1': 'Recuperação',
  'zona.2': 'Aeróbico leve',
  'zona.3': 'Aeróbico forte',
  'zona.4': 'Limiar',
  'zona.5': 'Máximo',
  'rec.pasoAPaso': 'PASSO A PASSO',
  'rec.bloques': 'TREINO · {n} BLOCOS',
  'rec.unBloque': 'TREINO · 1 BLOCO',
  'rec.nFases': 'TREINO · {n} FASES',
  'rec.enZona': 'Na zona',
  'rec.pulsoAlto': 'Frequência alta',
  'rec.pulsoBajo': 'Frequência baixa',
  'rec.tiempo': 'tempo',
  'rec.zonaPpm': '· zona {n} {nombre}',
  'rec.precision': 'Precisão do GPS: ±{m} m',
  'rec.senalDebil': '— sinal fraco, a distância pode ficar curta',
  'rec.avisosVoz': 'Avisos por voz e som a cada quilômetro',
  'rec.subirStrava': 'Enviar também para o Strava',
  'act.desnivel': 'm de ganho',
  'act.esfuerzo': 'Esforço {n}/10',
  'musc.pecho': 'Peito',
  'musc.hombros': 'Ombros',
  'musc.biceps': 'Bíceps',
  'musc.antebrazos': 'Antebraços',
  'musc.abdomen': 'Abdominais',
  'musc.oblicuos': 'Oblíquos',
  'musc.cuadriceps': 'Quadríceps',
  'musc.aductores': 'Adutores',
  'musc.tibial': 'Tibial',
  'musc.trapecio': 'Trapézio',
  'musc.dorsal': 'Dorsal',
  'musc.lumbar': 'Lombar',
  'musc.triceps': 'Tríceps',
  'musc.gluteos': 'Glúteos',
  'musc.isquios': 'Posteriores de coxa',
  'musc.gemelos': 'Panturrilhas',
  'img.fuerza': 'Força',
  'desc.ritmo': ' a {a} /km',
  'desc.zona': ' · zona {n}',
  'desc.recu': ' · recuperação {cant}',
  'desc.parado': ' parado',
  'fase.pasos': '{n} passos · {km} km · ~{min} min',
  'fase.anadirFase': '+ Adicionar fase',
  'fase.recuEntre': 'Recuperação entre as repetições',
  'fase.trotando': 'Trotando (se desmarcar, é parada total)',
  'fase.trasUltima': 'Incluir também depois da última repetição',
  'pie.escribenos': 'Fale com a gente',
  'pie.apoyar': 'Apoiar o projeto',
  'pie.lema': 'MyCoachRuns · Treine, melhore, avance',
  'entrar.servidorDijo': 'O servidor respondeu {n} ao verificar sua sessão.',
  'alumnos.sinNombre': 'Sem nome',
  'plan.conectaStrava': 'Conecte o Strava para as suas corridas sincronizarem sozinhas.',
  'plan.conectar': 'Conectar',
  'plan.sinCoach': 'Você ainda não está ligado a um treinador. Peça o link de convite dele.',
  'chat.sinCargar': 'Não deu para carregar as mensagens. Elas precisam de conexão.',
  'chat.sinCoach': 'Você ainda não está ligado a um treinador, então não há com quem conversar.',
  'chat.sinAlumnos': 'Você ainda não tem atletas.',
  'chat.sinLeer': '{n} não lidas',
  'chat.alDia': 'Em dia',
  'alumno.stravaOk': 'Strava conectado',
  'alumno.sinStrava': 'Sem Strava',
  'alumno.asignar': 'Atribuir treino',
} as const;
